refs JIRO-17 会員登録API
fesInformatics/jiro-stamp-rally-backend pull request #1
Opened 2023-11-12 08:04 UTC by tkr-ld

### 概要
* クリーンアーキテクチャっぽく会員登録API実装
* 極力ライブラリは使わない方針でORMマッパー使わずにやってみる
* 最終的にはメールアドレスは暗号化、パスワードはハッシュ化した方が良さそうだけど、デバッグが面倒になりそうなので、最後の方で実装したい！

### 動作確認
マイグレーションは後で追加するので一旦↓でCREATE TABLE
```sql
CREATE TABLE users (
    id            VARCHAR(255)    NOT NULL  PRIMARY KEY,
    mail_address  VARCHAR(255)    NOT NULL,
    password      VARCHAR(50)     NOT NULL
);
```
POSTMAN使ってたら`jiro-stamp-rally.postman_collection.json`をインポートしてもらえると 🙏

2024-01-07 01:07 UTC, mterada1228 commented on docker-compose.yml
> +  mysql:
[must] 

`mysql:8.0.27` には `arm` CPU 向けの image がないので、
M1 Mac 以降の PC でローカル環境を構築しようとすると image が Not Found になってしまう。

`platform: linux/amd64` を指定してもらえると助かる！

2024-01-08 00:11 UTC, mterada1228 requested changes
@tkr-ld 

開発ありがとう！Go 言語の経験ないので、
実装の良し悪しに関するレビューはできてない（スマン）

2点コメント残したのでご対応お願いします 🙏

2024-01-08 00:11 UTC, mterada1228 commented on jiro-stamp-rally/interface/controller/UserController.go
> +		err := c.interactor.Save(user.MailAddress, user.Password)
[imo] 

おそらくミニマムに実装することを目指しているとは思うのだけれども、
のちのログイン機能の実装のことを考えると、
メールアドレスの重複だけは避けられるとありがたい！

可能であれば、

* API 実行時にバリデーションとして重複チェックを実行
* カラムへの unique 制約の追加

こちらの実装をお願いできますと 🙏 （実装が大変なら片方のみでも良いと思います。）

2024-01-10 15:11 UTC, tkr-ld commented on docker-compose.yml
> +  mysql:
修正したす！
[1f86709](https://github.com/fesInformatics/jiro-stamp-rally-backend/pull/1/commits/1f867094d49e84f43ee5bd0268edb6d499463aee)

2024-01-10 15:13 UTC, tkr-ld commented on jiro-stamp-rally/interface/controller/UserController.go
> +		err := c.interactor.Save(user.MailAddress, user.Password)
ちょっとコミット少なくなっちゃって申し訳ないが、どっちも対応したー！
今無駄にライブラリ使わない挑戦をしてて、重複チェックとかじゃない文字数とかのバリデーションも自前で実装しようかなと思ったんだけど、結構めんどくなりそうなのでそこはライブラリ使うかもしれない、、
どっちにしろ別PRでやります！

2024-01-13 05:14 UTC, mterada1228 approved these changes
@tkr-ld 修正ありがとう！！レビューOKです！

2024-01-14 04:06 UTC, tkr-ld commented
レビューあざまっす！

2024-01-14 04:07 UTC, merged